image: node:latest

before_script:  
  - apt-get update -qq && apt-get install   
  
stages:      
  - setup    
  - build
  - test
  - deploy

setup-job:
  stage: setup
  script:
    - echo "Install all dependencies..." 
    - npm install        
    - echo "Install complete"
  artifacts:
    paths:
      - node_modules
    expire_in: 1h

build-job:       
  stage: build 
  script:         
    - echo "Run build"    
    - npm run build
    - echo "Build complete."
  artifacts:
    paths: 
      - dist
    expire_in: 1h

test-job:
  image: node:latest
  stage: test  
  script:         
    - apt-get -y install default-jre
    - npm install -g pnpm
    - echo "Install firebase tools"
    - npm install -g firebase-tools
    - echo "Run test"
    - firebase emulators:exec --project socketchat-7dd2a 'pnpm test'

deploy-job:      
  stage: deploy  
  environment: production 
  script:      
    - echo "Install firebase tools"
    - npm install -g firebase-tools
    - echo "Deploying application..."
    - firebase deploy --token $FIREBASE_TOKEN
    - echo "Application successfully deployed."
 