image: node:latest

before_script:  
  - apt-get update -qq && apt-get install

stages:          
  - build
  - test
  - deploy

build-job:       
  stage: build 
  script:
    - echo "Install all dependencies..." 
    - npm install  
    - echo "Run build"    
    - npm run build
    - echo "Build complete."
  artifacts:
    paths: 
      - dist
    expire_in: 30 days

test-job:
  stage: test
  script:
    - echo "TO_DO, add tests to pipeline"

deploy-job:      
  stage: deploy  
  environment: production 
  script:   
    - npm install -g firebase-tools
    - echo "Deploying application..."
    - firebase deploy --token $FIREBASE_TOKEN
    - echo "Application successfully deployed."
