image: node:latest

before_script:  
  - apt-get update -qq && apt-get install  
  - apt-get -y install default-jre
  
stages:          
  - build
  - test
  - deploy

build-job:       
  stage: build 
  script:    
    - echo "Install all dependencies..." 
    - npm install  
    - echo "Install firebase tools"
    - npm install -g firebase-tools
    - echo "Run build"    
    - npm run build
    - echo "Build complete."
  artifacts:
    paths: 
      - dist
    expire_in: 1h

test-job:
  stage: test  
  script:   
    - echo "Run test"
    - firebase emulators:exec --project socketchat-7dd2a 'pnpm test'

deploy-job:      
  stage: deploy  
  environment: production 
  script:      
    - echo "Deploying application..."
    - firebase deploy --token $FIREBASE_TOKEN
    - echo "Application successfully deployed."
 