image: node:latest

before_script:  
  - apt-get update -qq && apt-get install
  - npm install -g pnpm

stages:          
  - build
  - test
  - deploy

build-job:       
  stage: build 
  script:    
    - echo "Install all dependencies..." 
    - pnpm install  
    - echo "Run build"    
    - pnpm run build
    - echo "Build complete."
  artifacts:
    paths: 
      - dist
    expire_in: 1h
  only:
    - main

test-job:
  stage: test
  script:
    - echo "Install dependencies"
    - npm install
    #- echo "Setup"
    #- pnpm setup set bash 
    - echo "Install firebase"
    - npm install -g firebase-tools
    - echo "Run test"
    - firebase emulators:exec --project socketchat-7dd2a 'pnpm test'

deploy-job:      
  stage: deploy  
  environment: production 
  script:   
    - pnpm install -g firebase-tools
    - echo "Deploying application..."
    - firebase deploy --token $FIREBASE_TOKEN
    - echo "Application successfully deployed."
  only:
    - main
